// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

// The OnCommit / OnRollback / TxFromContext contract is implemented
// entirely in Quark's database/sql wrapper (the *Tx commit/rollback
// path) and is dialect-agnostic — no SQL is generated by the queue
// machinery itself. SQLite in-memory is therefore sufficient
// coverage; the six-engine integration matrix (CLAUDE.md Rule 1) is
// not required for this suite.

package quark_test

import (
	"context"
	"errors"
	"sync"
	"testing"

	"github.com/jcsvwinston/quark"
)

// ocRecorder is a tiny ordered sink the OnCommit / OnRollback
// callbacks write to. Each test gets its own instance — no globals,
// so these tests can run in parallel.
type ocRecorder struct {
	mu     sync.Mutex
	events []string
}

func (r *ocRecorder) add(s string) {
	r.mu.Lock()
	r.events = append(r.events, s)
	r.mu.Unlock()
}

func (r *ocRecorder) joined() string {
	r.mu.Lock()
	defer r.mu.Unlock()
	out := ""
	for i, e := range r.events {
		if i > 0 {
			out += ","
		}
		out += e
	}
	return out
}

type ocRow struct {
	ID   int64  `db:"id" pk:"true"`
	Name string `db:"name"`
}

func newOCClient(t *testing.T) *quark.Client {
	t.Helper()
	c, err := quark.New("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("new sqlite: %v", err)
	}
	t.Cleanup(func() { _ = c.Close() })
	if err := c.Migrate(context.Background(), &ocRow{}); err != nil {
		t.Fatalf("migrate: %v", err)
	}
	return c
}

// TestF5_5_OnCommit_FIFO_AfterCommit verifies that OnCommit
// callbacks fire in registration order after a successful commit.
func TestF5_5_OnCommit_FIFO_AfterCommit(t *testing.T) {
	t.Parallel()
	c := newOCClient(t)
	rec := &ocRecorder{}

	err := c.Tx(context.Background(), func(tx *quark.Tx) error {
		tx.OnCommit(func(context.Context) error { rec.add("c1"); return nil })
		tx.OnCommit(func(context.Context) error { rec.add("c2"); return nil })
		tx.OnCommit(func(context.Context) error { rec.add("c3"); return nil })
		// Nothing should have fired yet — still inside the tx.
		if rec.joined() != "" {
			t.Errorf("OnCommit fired before commit: %q", rec.joined())
		}
		return nil
	})
	if err != nil {
		t.Fatalf("Tx: %v", err)
	}
	if got := rec.joined(); got != "c1,c2,c3" {
		t.Errorf("OnCommit order = %q, want %q", got, "c1,c2,c3")
	}
}

// TestF5_5_OnCommit_ErrorDoesNotStopChain verifies that an error
// from one OnCommit callback is logged but the remaining callbacks
// still run — the commit already succeeded and cannot be undone.
func TestF5_5_OnCommit_ErrorDoesNotStopChain(t *testing.T) {
	t.Parallel()
	c := newOCClient(t)
	rec := &ocRecorder{}

	err := c.Tx(context.Background(), func(tx *quark.Tx) error {
		tx.OnCommit(func(context.Context) error { rec.add("c1"); return nil })
		tx.OnCommit(func(context.Context) error { rec.add("c2"); return errors.New("boom") })
		tx.OnCommit(func(context.Context) error { rec.add("c3"); return nil })
		return nil
	})
	if err != nil {
		t.Fatalf("Tx returned %v — OnCommit errors must NOT propagate to the caller", err)
	}
	if got := rec.joined(); got != "c1,c2,c3" {
		t.Errorf("chain stopped on error: got %q, want %q", got, "c1,c2,c3")
	}
}

// TestF5_5_OnCommit_DiscardedOnRollback verifies that OnCommit
// callbacks never fire when the transaction rolls back.
func TestF5_5_OnCommit_DiscardedOnRollback(t *testing.T) {
	t.Parallel()
	c := newOCClient(t)
	rec := &ocRecorder{}
	sentinel := errors.New("force-rollback")

	err := c.Tx(context.Background(), func(tx *quark.Tx) error {
		tx.OnCommit(func(context.Context) error { rec.add("c1"); return nil })
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("Tx returned %v, want sentinel", err)
	}
	if got := rec.joined(); got != "" {
		t.Errorf("OnCommit fired on rollback: %q", got)
	}
}

// TestF5_5_OnRollback_FiresOnRollbackOnly verifies the mirror
// contract: OnRollback fires (FIFO) on rollback and is discarded on
// commit.
func TestF5_5_OnRollback_FiresOnRollbackOnly(t *testing.T) {
	t.Parallel()
	c := newOCClient(t)

	// Rollback path.
	rbRec := &ocRecorder{}
	sentinel := errors.New("force-rollback")
	err := c.Tx(context.Background(), func(tx *quark.Tx) error {
		tx.OnRollback(func(context.Context) error { rbRec.add("r1"); return nil })
		tx.OnRollback(func(context.Context) error { rbRec.add("r2"); return nil })
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("Tx returned %v, want sentinel", err)
	}
	if got := rbRec.joined(); got != "r1,r2" {
		t.Errorf("OnRollback order = %q, want %q", got, "r1,r2")
	}

	// Commit path — OnRollback must NOT fire.
	commitRec := &ocRecorder{}
	err = c.Tx(context.Background(), func(tx *quark.Tx) error {
		tx.OnRollback(func(context.Context) error { commitRec.add("r1"); return nil })
		return nil
	})
	if err != nil {
		t.Fatalf("Tx: %v", err)
	}
	if got := commitRec.joined(); got != "" {
		t.Errorf("OnRollback fired on commit: %q", got)
	}
}

// TestF5_5_OnCommit_FiresAfterModelAfterHooks verifies the drain
// order: model After* hooks (F5-4) run before user OnCommit
// callbacks (F5-5). The recorder interleaves a CRUD whose
// AfterCreate is recorded (via the spy fixture) with an explicit
// OnCommit; AfterCreate must appear first.
//
// Reuses the spyOrder fixture + global recorder from
// hooks_tx_test.go, so this test runs SEQUENTIALLY (no t.Parallel).
func TestF5_5_OnCommit_FiresAfterModelAfterHooks(t *testing.T) {
	c := newSpyClient(t)
	rec := &hookRecorder{}
	defer setHookRecorder(rec)()

	ctx := context.Background()
	err := c.Tx(ctx, func(tx *quark.Tx) error {
		if err := quark.ForTx[spyOrder](ctx, tx).Create(&spyOrder{Name: "a"}); err != nil {
			return err
		}
		tx.OnCommit(func(context.Context) error {
			// Record through the same global recorder using a
			// distinct label so ordering is observable.
			rec.record("OnCommit")
			return nil
		})
		return nil
	})
	if err != nil {
		t.Fatalf("Tx: %v", err)
	}
	got := joinEvents(rec.snapshot())
	want := "BeforeCreate,AfterCreate,OnCommit"
	if got != want {
		t.Errorf("drain order = %q, want %q (model After* must precede user OnCommit)", got, want)
	}
}

// txAwareRow's AfterCreate uses quark.TxFromContext to reach the
// active transaction and register an OnCommit side-effect — the
// canonical pattern the helper exists for. A package-level pointer
// records whether the OnCommit fired so the test can assert it
// post-commit. Because the field is set from a hook dispatched on a
// zero *T, the signal travels through the shared txAwareFired flag,
// guarded for the race detector.
type txAwareRow struct {
	ID   int64  `db:"id" pk:"true"`
	Name string `db:"name"`
}

var (
	txAwareMu       sync.Mutex
	txAwareResolved bool // TxFromContext returned non-nil inside the hook
	txAwareFired    bool // the OnCommit registered from the hook fired
)

func (r *txAwareRow) AfterCreate(ctx context.Context) error {
	tx := quark.TxFromContext(ctx)
	txAwareMu.Lock()
	txAwareResolved = tx != nil
	txAwareMu.Unlock()
	if tx == nil {
		return nil
	}
	tx.OnCommit(func(context.Context) error {
		txAwareMu.Lock()
		txAwareFired = true
		txAwareMu.Unlock()
		return nil
	})
	return nil
}

// TestF5_5_TxFromContext_InsideHook verifies the end-to-end pattern:
// a model's AfterCreate hook resolves the active *Tx via
// TxFromContext (proving ForTx injected it into the hook's context)
// and registers an OnCommit that fires after the surrounding
// transaction commits.
//
// Runs sequentially: the txAware* package vars are shared state.
func TestF5_5_TxFromContext_InsideHook(t *testing.T) {
	txAwareMu.Lock()
	txAwareResolved, txAwareFired = false, false
	txAwareMu.Unlock()

	c, err := quark.New("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("new sqlite: %v", err)
	}
	t.Cleanup(func() { _ = c.Close() })
	ctx := context.Background()
	if err := c.Migrate(ctx, &txAwareRow{}); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	err = c.Tx(ctx, func(tx *quark.Tx) error {
		return quark.ForTx[txAwareRow](ctx, tx).Create(&txAwareRow{Name: "x"})
	})
	if err != nil {
		t.Fatalf("Tx: %v", err)
	}

	txAwareMu.Lock()
	resolved, fired := txAwareResolved, txAwareFired
	txAwareMu.Unlock()
	if !resolved {
		t.Error("TxFromContext returned nil inside AfterCreate — ForTx did not inject the tx into the hook context")
	}
	if !fired {
		t.Error("OnCommit registered from inside the hook did not fire post-commit")
	}

	// Negative: a bare context (no ForTx injection) resolves to nil.
	if got := quark.TxFromContext(context.Background()); got != nil {
		t.Errorf("TxFromContext(bare) = %p, want nil", got)
	}
}
