// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

package migrate_test

import (
	"net"
	"reflect"
	"testing"
	"time"

	"github.com/jcsvwinston/quark"
	"github.com/jcsvwinston/quark/internal/migrate"
	"github.com/jcsvwinston/quark/quarkdriver"
)

// TestClassify pins the Go half of the column-type pipeline: the portable
// kind a dialect is asked to spell for each Go type. The engine half is the
// type matrix (TestTypeMatrixIsCurrent).
func TestClassify(t *testing.T) {
	type named string
	k := func(kind quarkdriver.ColumnKind) quarkdriver.ColumnSpec { return quarkdriver.ColumnSpec{Kind: kind} }
	cases := []struct {
		typ  reflect.Type
		opts migrate.TypeOptions
		want quarkdriver.ColumnSpec
	}{
		{reflect.TypeOf(""), migrate.TypeOptions{}, k(quarkdriver.KindString)},
		{reflect.TypeOf(named("")), migrate.TypeOptions{Size: 9}, quarkdriver.ColumnSpec{Kind: quarkdriver.KindString, Size: 9}},
		{reflect.TypeOf(int8(0)), migrate.TypeOptions{}, k(quarkdriver.KindInt16)},
		{reflect.TypeOf(uint16(0)), migrate.TypeOptions{}, k(quarkdriver.KindInt16)},
		{reflect.TypeOf(int32(0)), migrate.TypeOptions{}, k(quarkdriver.KindInt32)},
		{reflect.TypeOf(0), migrate.TypeOptions{}, k(quarkdriver.KindInt64)},
		{reflect.TypeOf(time.Duration(0)), migrate.TypeOptions{}, k(quarkdriver.KindInt64)},
		{reflect.TypeOf(float32(0)), migrate.TypeOptions{}, k(quarkdriver.KindFloat32)},
		{reflect.TypeOf(float64(0)), migrate.TypeOptions{Precision: 18, Scale: 4},
			quarkdriver.ColumnSpec{Kind: quarkdriver.KindDecimal, Precision: 18, Scale: 4}},
		{reflect.TypeOf(""), migrate.TypeOptions{Precision: 18}, k(quarkdriver.KindString)}, // the hint is ignored off floats
		{reflect.TypeOf(false), migrate.TypeOptions{}, k(quarkdriver.KindBool)},
		{reflect.TypeOf(time.Time{}), migrate.TypeOptions{}, k(quarkdriver.KindTime)},
		{reflect.TypeOf([]byte{}), migrate.TypeOptions{}, k(quarkdriver.KindBytes)},
		{reflect.TypeOf(net.IP{}), migrate.TypeOptions{}, k(quarkdriver.KindIP)},
		{reflect.TypeOf([16]byte{}), migrate.TypeOptions{}, k(quarkdriver.KindUUID)},
		{reflect.TypeOf([]string{}), migrate.TypeOptions{}, quarkdriver.ColumnSpec{Kind: quarkdriver.KindArray, Elem: quarkdriver.KindString}},
		{reflect.TypeOf([]time.Time{}), migrate.TypeOptions{}, k(quarkdriver.KindJSON)},
		{reflect.TypeOf(map[string]any{}), migrate.TypeOptions{}, k(quarkdriver.KindJSON)},
		{reflect.TypeOf(quark.Range[time.Time]{}), migrate.TypeOptions{}, quarkdriver.ColumnSpec{Kind: quarkdriver.KindRange, Elem: quarkdriver.KindTime}},
		{reflect.TypeOf(quark.Range[string]{}), migrate.TypeOptions{}, k(quarkdriver.KindJSON)},
		{reflect.TypeOf(struct{ X int }{}), migrate.TypeOptions{}, k(quarkdriver.KindOther)},
	}
	for _, c := range cases {
		if got := migrate.Classify(c.typ, c.opts); got != c.want {
			t.Errorf("Classify(%s, %+v) = %+v, want %+v", c.typ, c.opts, got, c.want)
		}
	}
}

// TestPortableColumnTypes pins what a dialect that does not implement
// quarkdriver.ColumnTyper gets — the table the dialect API reference page
// publishes. Changing one of these changes the DDL of every such dialect.
func TestPortableColumnTypes(t *testing.T) {
	for spec, want := range map[quarkdriver.ColumnSpec]string{
		{Kind: quarkdriver.KindString}:                             "VARCHAR(255)",
		{Kind: quarkdriver.KindString, Size: 40}:                   "VARCHAR(40)",
		{Kind: quarkdriver.KindText}:                               "TEXT",
		{Kind: quarkdriver.KindInt16}:                              "SMALLINT",
		{Kind: quarkdriver.KindInt32}:                              "INTEGER",
		{Kind: quarkdriver.KindInt64}:                              "BIGINT",
		{Kind: quarkdriver.KindFloat32}:                            "REAL",
		{Kind: quarkdriver.KindFloat64}:                            "DOUBLE PRECISION",
		{Kind: quarkdriver.KindDecimal, Precision: 10, Scale: 2}:   "DECIMAL(10,2)",
		{Kind: quarkdriver.KindBool}:                               "BOOLEAN",
		{Kind: quarkdriver.KindTime}:                               "TIMESTAMP",
		{Kind: quarkdriver.KindBytes}:                              "BLOB",
		{Kind: quarkdriver.KindJSON}:                               "TEXT",
		{Kind: quarkdriver.KindUUID}:                               "CHAR(36)",
		{Kind: quarkdriver.KindIP}:                                 "VARCHAR(45)",
		{Kind: quarkdriver.KindArray, Elem: quarkdriver.KindInt64}: "TEXT",
		{Kind: quarkdriver.KindRange, Elem: quarkdriver.KindTime}:  "TEXT",
		{Kind: quarkdriver.KindOther}:                              "TEXT",
	} {
		if got := migrate.PortableColumnType(spec); got != want {
			t.Errorf("PortableColumnType(%+v) = %q, want %q", spec, got, want)
		}
	}
	if def, typ := migrate.PortableAutoIncrement(); def != "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" || typ != "BIGINT" {
		t.Errorf("PortableAutoIncrement() = %q, %q", def, typ)
	}
	if migrate.PortableBoolLiteral(true) != "TRUE" || migrate.PortableBoolLiteral(false) != "FALSE" {
		t.Error("the portable boolean literals are TRUE and FALSE")
	}
}
