// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/jcsvwinston/quark"
)

// GeneratedFileName is the file each package's registrations are written to.
const GeneratedFileName = "quark_gen.go"

// Render produces the gofmt'd contents of a package's quark_gen.go. The file
// stamps the contract version it was generated against (a literal, not a
// reference to GenContractVersion, so a stale file keeps its old version and
// the runtime's version gate can detect it), and registers per model a
// version+hash, plus the inert F6-1 stub scanner/binder.
func Render(pm PackageModels) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by \"quark gen\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//quark:gen v%d\n\n", quark.GenContractVersion)
	fmt.Fprintf(&b, "package %s\n\n", pm.PkgName)
	b.WriteString("import (\n\t\"reflect\"\n\n\t\"github.com/jcsvwinston/quark\"\n)\n\n")
	b.WriteString("func init() {\n")
	for i, m := range pm.Models {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\tquark.RegisterGeneratedMeta(reflect.TypeOf(%s{}), quark.GeneratedMeta{\n", m.Name)
		fmt.Fprintf(&b, "\t\tContractVersion: %d,\n", quark.GenContractVersion)
		fmt.Fprintf(&b, "\t\tModelHash:       %q,\n", m.Hash)
		b.WriteString("\t})\n")
		fmt.Fprintf(&b, "\tquark.RegisterTypedScanner(reflect.TypeOf(%s{}), quark.StubScanner)\n", m.Name)
		fmt.Fprintf(&b, "\tquark.RegisterTypedBinder(reflect.TypeOf(%s{}), quark.StubBinder)\n", m.Name)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n---\n%s", err, b.String())
	}
	return src, nil
}

// Generate loads the packages matching patterns and writes a quark_gen.go
// into each package that contains models. It returns the paths written.
func Generate(patterns ...string) ([]string, error) {
	pkgs, err := Load(patterns...)
	if err != nil {
		return nil, err
	}
	var written []string
	for _, pm := range pkgs {
		if pm.Dir == "" {
			return written, fmt.Errorf("package %s: no source directory to write to", pm.PkgPath)
		}
		src, err := Render(pm)
		if err != nil {
			return written, err
		}
		out := filepath.Join(pm.Dir, GeneratedFileName)
		if err := os.WriteFile(out, src, 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", out, err)
		}
		written = append(written, out)
	}
	return written, nil
}
