// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/jcsvwinston/quark"
)

// GeneratedFileName is the file each package's registrations are written to.
const GeneratedFileName = "quark_gen.go"

// scanFuncName / bindFuncName are the generated scanner/binder identifiers
// for a model. The distinctive prefix avoids colliding with user code in the
// same package.
func scanFuncName(model string) string { return "quarkgenScan" + model }
func bindFuncName(model string) string { return "quarkgenBind" + model }

var integerKinds = map[string]bool{
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
}

// insertBinderPK returns the model's primary-key field and true when the
// model is eligible for a generated INSERT binder: exactly one field tagged
// pk, of an integer kind — the auto-increment case buildInsert skips when
// zero. Composite, string, or non-integer PKs fall back to the reflection
// bind path (StubBinder), so the generated binder never has to reproduce
// their zero-detection rules.
func insertBinderPK(m ModelDef) (quark.ModelField, bool) {
	var pk quark.ModelField
	count := 0
	for _, f := range m.Fields {
		if f.IsPK {
			pk = f
			count++
		}
	}
	if count != 1 || !integerKinds[quark.CanonicalType(pk.GoType)] {
		return quark.ModelField{}, false
	}
	return pk, true
}

// Render produces the gofmt'd contents of a package's quark_gen.go. The file
// stamps the contract version it was generated against (a literal, not a
// reference to GenContractVersion, so a stale file keeps its old version and
// the runtime's version gate can detect it), registers per model a
// version+hash, a typed scanner, and — for integer-PK models — a typed INSERT
// binder (other models register the stub binder and bind via reflection).
func Render(pm PackageModels) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by \"quark gen\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//quark:gen v%d\n\n", quark.GenContractVersion)
	fmt.Fprintf(&b, "package %s\n\n", pm.PkgName)
	b.WriteString("import (\n\t\"database/sql\"\n\t\"reflect\"\n\t\"strings\"\n\n\t\"github.com/jcsvwinston/quark\"\n)\n\n")

	b.WriteString("func init() {\n")
	for i, m := range pm.Models {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\tquark.RegisterGeneratedMeta(reflect.TypeOf(%s{}), quark.GeneratedMeta{\n", m.Name)
		fmt.Fprintf(&b, "\t\tContractVersion: %d,\n", quark.GenContractVersion)
		fmt.Fprintf(&b, "\t\tModelHash:       %q,\n", m.Hash)
		b.WriteString("\t})\n")
		fmt.Fprintf(&b, "\tquark.RegisterTypedScanner(reflect.TypeOf(%s{}), %s)\n", m.Name, scanFuncName(m.Name))
		if _, ok := insertBinderPK(m); ok {
			fmt.Fprintf(&b, "\tquark.RegisterTypedBinder(reflect.TypeOf(%s{}), %s)\n", m.Name, bindFuncName(m.Name))
		} else {
			fmt.Fprintf(&b, "\tquark.RegisterTypedBinder(reflect.TypeOf(%s{}), quark.StubBinder)\n", m.Name)
		}
	}
	b.WriteString("}\n")

	// One typed scanner per model: map result columns to field pointers by
	// name (no reflection), routing each through quark.ScanTarget so special
	// types (time.Time, JSON[T], …) scan exactly as the reflection path does.
	//
	// Only fields with a db tag get a case (that is the set extractFields
	// returns). The reflection path additionally matches columns to untagged
	// fields by snake_cased field name; the generated scanner does not, so a
	// model relying on that fallback would scan such columns into discard.
	// In practice persisted fields carry db tags; this is noted as a known
	// limitation in the codegen guide.
	for _, m := range pm.Models {
		b.WriteString("\n")
		fmt.Fprintf(&b, "func %s(rows *sql.Rows, dest any) error {\n", scanFuncName(m.Name))
		fmt.Fprintf(&b, "\tm := dest.(*%s)\n", m.Name)
		b.WriteString("\tcols, err := rows.Columns()\n")
		b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		b.WriteString("\tscanDest := make([]any, len(cols))\n")
		b.WriteString("\tfor i, c := range cols {\n")
		b.WriteString("\t\tswitch strings.ToLower(c) {\n")
		for _, f := range m.Fields {
			fmt.Fprintf(&b, "\t\tcase %q:\n", strings.ToLower(f.Column))
			fmt.Fprintf(&b, "\t\t\tscanDest[i] = quark.ScanTarget(&m.%s)\n", f.Name)
		}
		b.WriteString("\t\tdefault:\n")
		b.WriteString("\t\t\tvar discard any\n")
		b.WriteString("\t\t\tscanDest[i] = &discard\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn rows.Scan(scanDest...)\n")
		b.WriteString("}\n")
	}

	// One INSERT binder per eligible model: build (columns, args) without
	// reflection. The primary key is skipped when zero (auto-increment), every
	// other db-tagged field is always bound, mirroring buildInsert. Columns are
	// unquoted and args raw — buildInsert quotes columns, generates
	// placeholders, and appends any tenant column. Only BindInsert is emitted
	// in this phase; BindUpdate returns ErrGeneratedStub so the write path
	// falls back to reflection for updates.
	for _, m := range pm.Models {
		pk, ok := insertBinderPK(m)
		if !ok {
			continue
		}
		b.WriteString("\n")
		fmt.Fprintf(&b, "func %s(entity any, mode quark.BindMode) (cols []string, args []any, err error) {\n", bindFuncName(m.Name))
		fmt.Fprintf(&b, "\tm := entity.(*%s)\n", m.Name)
		b.WriteString("\tif mode != quark.BindInsert {\n")
		b.WriteString("\t\treturn nil, nil, quark.ErrGeneratedStub\n")
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tcols = make([]string, 0, %d)\n", len(m.Fields))
		fmt.Fprintf(&b, "\targs = make([]any, 0, %d)\n", len(m.Fields))
		for _, f := range m.Fields {
			if f.IsPK && f.Name == pk.Name {
				fmt.Fprintf(&b, "\tif m.%s != 0 {\n", f.Name)
				fmt.Fprintf(&b, "\t\tcols = append(cols, %q)\n", f.Column)
				fmt.Fprintf(&b, "\t\targs = append(args, m.%s)\n", f.Name)
				b.WriteString("\t}\n")
				continue
			}
			fmt.Fprintf(&b, "\tcols = append(cols, %q)\n", f.Column)
			fmt.Fprintf(&b, "\targs = append(args, m.%s)\n", f.Name)
		}
		b.WriteString("\treturn cols, args, nil\n")
		b.WriteString("}\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n---\n%s", err, b.String())
	}
	return src, nil
}

// Generate loads the packages matching patterns and writes a quark_gen.go
// into each package that contains models. It returns the paths written.
func Generate(patterns ...string) ([]string, error) {
	pkgs, err := Load(patterns...)
	if err != nil {
		return nil, err
	}
	var written []string
	for _, pm := range pkgs {
		if pm.Dir == "" {
			return written, fmt.Errorf("package %s: no source directory to write to", pm.PkgPath)
		}
		src, err := Render(pm)
		if err != nil {
			return written, err
		}
		out := filepath.Join(pm.Dir, GeneratedFileName)
		if err := os.WriteFile(out, src, 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", out, err)
		}
		written = append(written, out)
	}
	return written, nil
}
