// Code generated by "quark gen"; DO NOT EDIT.
//quark:gen v1

package sample

import (
	"reflect"

	"github.com/jcsvwinston/quark"
)

func init() {
	quark.RegisterGeneratedMeta(reflect.TypeOf(Account{}), quark.GeneratedMeta{
		ContractVersion: 1,
		ModelHash:       "e987c366ce4ce84214baf0d4f0b5d71c0ea4c5cf9618f374b5c4e9814703b276",
	})
	quark.RegisterTypedScanner(reflect.TypeOf(Account{}), quark.StubScanner)
	quark.RegisterTypedBinder(reflect.TypeOf(Account{}), quark.StubBinder)
}
