// Code generated by "quark gen"; DO NOT EDIT.
//quark:gen v2

package sample

import (
	"database/sql"
	"reflect"
	"strings"

	"github.com/jcsvwinston/quark"
)

func init() {
	quark.RegisterGeneratedMeta(reflect.TypeOf(Account{}), quark.GeneratedMeta{
		ContractVersion: 2,
		ModelHash:       "e987c366ce4ce84214baf0d4f0b5d71c0ea4c5cf9618f374b5c4e9814703b276",
	})
	quark.RegisterTypedScanner(reflect.TypeOf(Account{}), quarkgenScanAccount)
	quark.RegisterTypedBinder(reflect.TypeOf(Account{}), quark.StubBinder)
}

func quarkgenScanAccount(rows *sql.Rows, dest any) error {
	m := dest.(*Account)
	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	scanDest := make([]any, len(cols))
	for i, c := range cols {
		switch strings.ToLower(c) {
		case "id":
			scanDest[i] = quark.ScanTarget(&m.ID)
		case "email":
			scanDest[i] = quark.ScanTarget(&m.Email)
		case "age":
			scanDest[i] = quark.ScanTarget(&m.Age)
		case "balance":
			scanDest[i] = quark.ScanTarget(&m.Balance)
		case "active":
			scanDest[i] = quark.ScanTarget(&m.Active)
		case "settings":
			scanDest[i] = quark.ScanTarget(&m.Settings)
		case "nickname":
			scanDest[i] = quark.ScanTarget(&m.Nickname)
		case "created_at":
			scanDest[i] = quark.ScanTarget(&m.CreatedAt)
		case "updated_at":
			scanDest[i] = quark.ScanTarget(&m.UpdatedAt)
		default:
			var discard any
			scanDest[i] = &discard
		}
	}
	return rows.Scan(scanDest...)
}
