// Code generated by "quark gen"; DO NOT EDIT.
//quark:gen v3

package sample

import (
	"database/sql"
	"reflect"
	"strings"
	"time"

	"github.com/jcsvwinston/quark"
)

func init() {
	quark.RegisterGeneratedMeta(reflect.TypeOf(Account{}), quark.GeneratedMeta{
		ContractVersion: 3,
		ModelHash:       "e987c366ce4ce84214baf0d4f0b5d71c0ea4c5cf9618f374b5c4e9814703b276",
	})
	quark.RegisterTypedScanner(reflect.TypeOf(Account{}), quarkgenScanAccount)
	quark.RegisterTypedBinder(reflect.TypeOf(Account{}), quarkgenBindAccount)
}

func quarkgenScanAccount(rows *sql.Rows, dest any) error {
	m := dest.(*Account)
	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	scanDest := make([]any, len(cols))
	for i, c := range cols {
		switch strings.ToLower(c) {
		case "id":
			scanDest[i] = quark.ScanTarget(&m.ID)
		case "email":
			scanDest[i] = quark.ScanTarget(&m.Email)
		case "age":
			scanDest[i] = quark.ScanTarget(&m.Age)
		case "balance":
			scanDest[i] = quark.ScanTarget(&m.Balance)
		case "active":
			scanDest[i] = quark.ScanTarget(&m.Active)
		case "settings":
			scanDest[i] = quark.ScanTarget(&m.Settings)
		case "nickname":
			scanDest[i] = quark.ScanTarget(&m.Nickname)
		case "created_at":
			scanDest[i] = quark.ScanTarget(&m.CreatedAt)
		case "updated_at":
			scanDest[i] = quark.ScanTarget(&m.UpdatedAt)
		default:
			var discard any
			scanDest[i] = &discard
		}
	}
	return rows.Scan(scanDest...)
}

func quarkgenBindAccount(entity any, mode quark.BindMode) (cols []string, args []any, err error) {
	m := entity.(*Account)
	if mode != quark.BindInsert {
		return nil, nil, quark.ErrGeneratedStub
	}
	cols = make([]string, 0, 9)
	args = make([]any, 0, 9)
	if m.ID != 0 {
		cols = append(cols, "id")
		args = append(args, m.ID)
	}
	cols = append(cols, "email")
	args = append(args, m.Email)
	cols = append(cols, "age")
	args = append(args, m.Age)
	cols = append(cols, "balance")
	args = append(args, m.Balance)
	cols = append(cols, "active")
	args = append(args, m.Active)
	cols = append(cols, "settings")
	args = append(args, m.Settings)
	cols = append(cols, "nickname")
	args = append(args, m.Nickname)
	cols = append(cols, "created_at")
	args = append(args, m.CreatedAt)
	cols = append(cols, "updated_at")
	args = append(args, m.UpdatedAt)
	return cols, args, nil
}

// AccountColumns provides typed, compile-time-checked column accessors for Account.
var AccountColumns = struct {
	ID        quark.TypedColumn[int64]
	Email     quark.TypedStringColumn
	Age       quark.TypedColumn[int]
	Balance   quark.TypedColumn[float64]
	Active    quark.TypedColumn[bool]
	Settings  quark.TypedColumn[quark.JSON[string]]
	Nickname  quark.TypedColumn[sql.Null[string]]
	CreatedAt quark.TypedColumn[time.Time]
	UpdatedAt quark.TypedColumn[*time.Time]
}{
	ID:        quark.NewTypedColumn[int64]("id"),
	Email:     quark.NewTypedStringColumn("email"),
	Age:       quark.NewTypedColumn[int]("age"),
	Balance:   quark.NewTypedColumn[float64]("balance"),
	Active:    quark.NewTypedColumn[bool]("active"),
	Settings:  quark.NewTypedColumn[quark.JSON[string]]("settings"),
	Nickname:  quark.NewTypedColumn[sql.Null[string]]("nickname"),
	CreatedAt: quark.NewTypedColumn[time.Time]("created_at"),
	UpdatedAt: quark.NewTypedColumn[*time.Time]("updated_at"),
}
